### PR TITLE
Restrict scope guard to noexcept functions

### LINKED ISSUE #1550: Restrict scope guard to accept only noexcept functions
A clang-tidy check is complaining that calling an arbitrary function in the destructor of the scope guard can throw an exception. We should restrict scope guard to only accept `noexcept` invokable types.
The suggestion here is to add a `static_assert` in the class to check if invoking the object might throw, and then go through the existing uses of scope guard and add `noexcept` declarations. After looking at the code, we should be able to declare most of the scope guard lambdas `noexcept` without any further code changes, but some cases might need other workarounds.

### PR DESCRIPTION
**Pull request by riemass**
Like discussed before, this PR adds a static assert to the scope guard making sure the provided function is noexcept. 
I've also went and added `noexcept` to all lambdas so the solution compiles without issues, however clang tidy does complain a lot about some cases where the lambdas might throw under rare circumstances. 

Closes #1550.

### CODE REVIEW

File: examples/qtsupport/chatwidget.cpp [hunk 1]
```diff
@@ -71,7 +71,8 @@ void ChatWidget::init(actor_system& system, const std::string& name,
 }
 
 void ChatWidget::sendChatMessage() {
-  auto cleanup = detail::make_scope_guard([=] { input()->setText(QString()); });
+  auto cleanup
+    = detail::make_scope_guard([=]() noexcept { input()->setText(QString()); });
```
Comment (Neverlord) [inline examples/qtsupport/chatwidget.cpp:75]: This can just move to the end of the function. There is one `return` in the `if-else` tree that we can just remove because it does nothing.

File: libcaf_core/caf/detail/parser/read_config.hpp [hunk 2]
```diff
@@ -192,7 +192,7 @@ void read_config_map(State& ps, Consumer&& consumer) {
 template <class State, class Consumer>
 void read_config_uri(State& ps, Consumer&& consumer) {
   uri_builder builder;
-  auto g = make_scope_guard([&] {
+  auto g = make_scope_guard([&]() noexcept {
     if (ps.code <= pec::trailing_character)
       consumer.value(builder.make());
```
Comment (Neverlord) [inline libcaf_core/caf/detail/parser/read_config.hpp:197]: Can throw, because it allocates memory. Maybe we can just add something to the testing DSL for this instead of using scope guards. Applies to a lot of other places as well, so let me think a bit about this.

File: libcaf_core/caf/logger.hpp [hunk 3]
```diff
@@ -353,8 +353,10 @@ class CAF_CORE_EXPORT logger {
 #define CAF_PUSH_AID(aarg)                                                     \
   caf::actor_id CAF_PP_UNIFYN(caf_aid_tmp)                                     \
     = caf::logger::thread_local_aid(aarg);                                     \
-  auto CAF_PP_UNIFYN(caf_aid_tmp_guard) = caf::detail::make_scope_guard(       \
-    [=] { caf::logger::thread_local_aid(CAF_PP_UNIFYN(caf_aid_tmp)); })
+  auto CAF_PP_UNIFYN(caf_aid_tmp_guard)                                        \
+    = caf::detail::scope_guard([=]() noexcept {                                \
+        caf::logger::thread_local_aid(CAF_PP_UNIFYN(caf_aid_tmp));             \
+      })
```
Comment (Neverlord) [inline libcaf_core/caf/logger.hpp:359]: If we declare this lambda `noexcept`, we'll also need to declare `thread_local_aid` `noexcept`.

File: libcaf_core/tests/legacy/dsl.cpp [hunk 4]
```diff
@@ -252,7 +252,7 @@ SCENARIO("passing requirements increment the 'good' counter") {
       auto silent_expr = [&] {                                                 \
         auto bk = caf::test::logger::instance().make_quiet();                  \
         auto guard = caf::detail::make_scope_guard(                            \
-          [bk] { caf::test::logger::instance().levels(bk); });                 \
+          [bk]() noexcept { caf::test::logger::instance().levels(bk); });      \
```
Comment (Neverlord) [inline libcaf_core/tests/legacy/dsl.cpp:255]: Adding `noexcept` here requires that we also add `noexcept` to `levels` in `libcaf_test/caf/test/unit_test.hpp`.

File: libcaf_io/tests/legacy/io/unpublish.cpp [hunk 5]
```diff
@@ -68,7 +68,7 @@ BEGIN_FIXTURE_SCOPE(fixture)
 
 CAF_TEST(actors can become unpublished) {
   auto testee = mars.sys.spawn<dummy>(ssp);
-  auto guard = detail::make_scope_guard([&] {
+  auto guard = detail::make_scope_guard([&]() noexcept {
     // The MM holds a reference to this actor publishing it, so we need to kill
     // it manually.
     anon_send_exit(testee, exit_reason::user_shutdown);
```
Comment (Neverlord) [inline libcaf_io/tests/legacy/io/unpublish.cpp:74]: Just put this at the end instead of using a scope guard.

**Review by Neverlord — CHANGES_REQUESTED** [review]

**Comment by Neverlord** [comment]
Please rebase to pass CI again.

File: libcaf_core/caf/detail/parser/read_config.hpp (hunk 2 above)
Comment (riemass) [reply libcaf_core/caf/detail/parser/read_config.hpp:197]: In the case we don't have enough memory here, we're having an problem anyways, whether we throw in the scope guard destructor or in an noexcept function. Not sure how to handle out-of-memory conditions, it falls back to the custom allocator and system resources.

File: libcaf_core/caf/logger.hpp (hunk 3 above)
Comment (riemass) [reply libcaf_core/caf/logger.hpp:359]: I will add it to logger. Just a note here, I tried following the chain and adding `noexcept` everywhere and failed. As you noted in the previous comment as well, there are places where it's just not possible.

File: libcaf_core/caf/detail/format.cpp [hunk 6]
```diff
@@ -309,7 +309,7 @@ void copy_verbatim(ParserState& ps, copy_state& cs);
 template <class ParserState>
 void copy_formatted(ParserState& ps, copy_state& cs) {
   cs.reset();
-  auto guard = make_scope_guard([&] {
+  auto guard = make_scope_guard([&]() noexcept {
     if (ps.code <= pec::trailing_character)
       cs.fn = copy_verbatim<string_parser_state>;
```
Comment (Neverlord) [inline libcaf_core/caf/detail/format.cpp:314]: Looks like I didn't spot this last time. Please move below `fin()` to be consistent with the other recent changes and drop the include for `scope_guard`.

File: libcaf_core/caf/detail/json.cpp [hunk 7]
```diff
@@ -215,7 +215,7 @@ template <class ParserState, class Consumer>
 void read_json_null_or_nan(ParserState& ps, Consumer consumer) {
   enum { nil, is_null, is_nan };
   auto res_type = nil;
-  auto g = make_scope_guard([&] {
+  auto g = make_scope_guard([&]() noexcept {
```
Comment (Neverlord) [inline libcaf_core/caf/detail/json.cpp:218]: Same, move below `fin()` and drop scope guards.

File: libcaf_core/caf/scheduled_actor.cpp [hunk 8]
```diff
@@ -280,7 +280,7 @@ resumable::resume_result scheduled_actor::resume(execution_unit* ctx,
   if (!activate(ctx))
     return resumable::done;
   size_t consumed = 0;
-  auto guard = detail::make_scope_guard([this, &consumed] {
+  auto guard = detail::make_scope_guard([this, &consumed]() noexcept {
     CAF_LOG_DEBUG("resume consumed" << consumed << "messages");
```
Comment (Neverlord) [inline libcaf_core/caf/scheduled_actor.cpp:284]: Logging might throw.

```suggestion
```

File: libcaf_test/caf/test/outline.cpp [hunk 9]
```diff
@@ -107,7 +107,7 @@ void outline::run() {
     }
   }
   ctx_->parameters = ctx_->example_parameters[ctx_->example_id];
-  auto guard = detail::make_scope_guard([this] {
+  auto guard = detail::make_scope_guard([this]() noexcept {
     auto& ptr = ctx_->steps[std::make_pair(0, ctx_->example_id)];
```
Comment (Neverlord) [inline libcaf_test/caf/test/outline.cpp:111]: This can technically throw, so clang-tidy might complain later about it. We can just move it out of the lambda and capture it instead.

**Review by Neverlord — CHANGES_REQUESTED** [review]
Small nits, otherwise looks good.

**Review by Neverlord — APPROVED** [review]
