### PR TITLE
Fix potential segfault with logging enabled

### LINKED ISSUE #878: Potential segfault when using streams with logging enabled
When streaming a type that wasn't added to the uniform type info list (e.g. when using whitelisted types), CAF segfaults in the constructor of `inbound_path` if the log level is DEBUG or lower.

### PR DESCRIPTION
**Pull request by Neverlord**
Close #878.

### CODE REVIEW

File: libcaf_core/caf/uniform_type_info_map.hpp [hunk 1]
```diff
@@ -75,32 +75,45 @@ class uniform_type_info_map {
...
+
+  /// Lock for accessing `ad_hoc_`.`
   mutable detail::shared_spinlock ad_hoc_mtx_;
 
-  // message type names
+  /// Names of builtin types.
   std::array<std::string, type_nrs - 1> builtin_names_;
+
+  /// Displayed name for unknown types.
+  std::string default_type_name_;
```
Comment (josephnoir) [inline libcaf_core/caf/uniform_type_info_map.hpp]: This could be const?

Comment (Neverlord) [reply libcaf_core/caf/uniform_type_info_map.hpp]: Making member variables `const` comes with many strings attached (makes a type unmovable, for example). Generally, I wouldn't put `const` to member variables except for a few niche applications.

Comment (josephnoir) [reply libcaf_core/caf/uniform_type_info_map.hpp]: I see.
