### PR TITLE
Fix function object lifetimes in actions

### LINKED ISSUE #698: Canceled timeouts hold onto actor references until they expire, thus blocking program shutdown
This is the first issue I'm filing with actor-framework. I'm new to most of its concepts and this might be an error on my end.

The following test program is supposed to chain two actors together. The message flow is supposed to be caf_main -> parent -> child -> parent handler -> caf_main handler. The timeout in the call from the parent to the child seems to hold up the main process from exiting. Setting it to `seconds(2)` makes the whole process take 2 seconds to exit. Setting it to `infinite` makes it exit immediately. Is this expected?

I convinced myself through a bunch of aout's that the control flow is as I expect it to be.

```
#include <chrono>
#include <string>
#include <iostream>
#include <unordered_map>

#include "caf/all.hpp"

using namespace caf;
using namespace std;
using namespace std::chrono;

using ping_atom = atom_constant<atom("ping")>;
using pong_atom = atom_constant<atom("pong")>;

behavior fwd_actor(event_based_actor* self, const actor* child) {
  return {
    [=](ping_atom) -> result<int> {
      auto rp = self->make_response_promise<int>();
      if (child != nullptr) {
        aout(self) << "ping parent -> child" << endl;
        self->request(*child, seconds(2), ping_atom::value).then([=](int i) mutable {
          aout(self) << "parent -> child done, result: " << i << endl;
          rp.deliver(i);
        }, [=](error& e){
          aout(self) << self->system().render(e) << std::endl;
        });
        aout(self) << "parent done" << endl;
      } else {
        aout(self) << "ping in the child" << endl;
        rp.deliver(2);
      }
    return rp;
    },
  };
}

void caf_main(actor_system& system) {
  scoped_actor self(system);
  auto child = system.spawn(fwd_actor, nullptr);
  auto parent = system.spawn(fwd_actor, &child);
  self->request(parent, seconds(4), ping_atom::value).receive(
    [&](int i) {
      aout(self) << "main call done, result: " << i << endl;
    },
    [&](error& e) {
      cout << self->system().render(e) << std::endl;
  });

  aout(self) << "Done" << endl;
}

CAF_MAIN();
```

Compile with `g++ -g --std=c++17 -l caf_core -o chain chain.cpp`.

```
time ./chain
ping parent -> child
parent done
ping in the child
parent -> child done, result: 2
main call done, result: 2
Done
./chain  0.01s user 0.03s system 2% cpu 2.034 total
```

### PR DESCRIPTION
**Pull request by riemass**
Closes #698.
When disposing actions, we would tag the state enum as disposed, but still keep the function object until all the intrusive pointers go out of scope. Since the function can have it's own state, like a strong actor pointer, we would block the system until the action would timeout, even thought it is disposed.

### CODE REVIEW

**Comment by riemass** [comment]
> Ok, I can kinda see how that could be related... But where's a test for it? 🙂

I've confirmed it with the code from the ticket. I've pushed a unit test. The last check, dropping the strong refs to 0, is what failed without the committed code.

File: libcaf_core/caf/action.hpp [hunk 1]
```diff
@@ -132,17 +132,22 @@ inline bool operator!=(const action& lhs, const action& rhs) noexcept {
...
 
+  ~default_action_impl() {
+    if (state_.load() == action::state::scheduled)
+      f_.~F();
+  }
+
   void dispose() override {
-    state_ = action::state::disposed;
+    state_.store(action::state::disposed);
+    f_.~F();
```
Comment (Neverlord) [inline libcaf_core/caf/action.hpp:150]: Should try to set `state_` to `disposed` atomically and only call the destructor when transitioning from another state.

```
    state_.store(action::state::disposed);
    f_.~F();
```

File: libcaf_core/tests/legacy/mixin/requester.cpp [hunk 2]
```diff
@@ -363,4 +363,23 @@ TEST_CASE("GH-1299 regression blocking") {
   }
 }
 
+TEST_CASE("GH-698 regression responding to a request drops the strong "
+          "reference count") {
+  auto weak_client_ref = [this] {
+    return actor_cast<weak_actor_ptr>(
+      sys.spawn([this](event_based_actor* self) {
+        self->request(adding_server, std::chrono::seconds{10}, 1, 2)
```
Comment (Neverlord) [inline libcaf_core/tests/legacy/mixin/requester.cpp:371]:
```suggestion
        self->request(adding_server, 10s, 1, 2)
```

(plus `using namespace std::literals`)

File: libcaf_core/tests/legacy/mixin/requester.cpp [hunk 3]
```diff
@@ -363,4 +363,23 @@ TEST_CASE("GH-1299 regression blocking") {
   }
 }
 
+TEST_CASE("GH-698 regression responding to a request drops the strong "
+          "reference count") {
```
Comment (Neverlord) [inline libcaf_core/tests/legacy/mixin/requester.cpp:367]:
```suggestion
TEST_CASE("actors cancel request timeouts after receiving a response") {
```

File: libcaf_core/tests/legacy/mixin/requester.cpp [hunk 4]
```diff
@@ -363,4 +363,23 @@ TEST_CASE("GH-1299 regression blocking") {
...
+  auto weak_client_ref = [this] {
+    return actor_cast<weak_actor_ptr>(
+      sys.spawn([this](event_based_actor* self) {
```
Comment (Neverlord) [inline libcaf_core/tests/legacy/mixin/requester.cpp:370]: This is not what I would expect here. By only having a weak ref to this actor, we will terminate it as unreachable once it processes the response message.

The reported bug was about *not* terminating the actor. The fixed version must work with just:

```suggestion
  auto client = sys.spawn([this](event_based_actor* self) {
```

File: libcaf_core/tests/legacy/mixin/requester.cpp [hunk 5]
```diff
@@ -363,4 +363,23 @@ TEST_CASE("GH-1299 regression blocking") {
...
+      }));
+  }();
+  CHECK_EQ(weak_client_ref->strong_refs, 1u);
+  run_once();
+  CHECK_EQ(weak_client_ref->strong_refs, 2u);
+  expect((int, int), from(weak_client_ref).to(adding_server).with(1, 2));
+  CHECK_EQ(weak_client_ref->strong_refs, 2u);
+  expect((int), from(adding_server).to(weak_client_ref));
+  CHECK_EQ(weak_client_ref->strong_refs, 0u);
+  CHECK_EQ(*result, result_type{3});
```
Comment (Neverlord) [inline libcaf_core/tests/legacy/mixin/requester.cpp:382]: I don't get why we are tracking the reference count here if the issue was about timeouts not being cancelled. I would have expected something like this:

```
  run_once();
  expect((int, int), from(client).to(adding_server).with(1, 2));
  CHECK(sched.has_pending_timeout());
  expect((int), from(adding_server).to(client));
  CHECK(!sched.has_pending_timeout());
```

I would also expect a second test that covers the error case, i.e., if the client receives an error instead of an actual result.

**Review by Neverlord — CHANGES_REQUESTED** [review]

File: libcaf_core/tests/legacy/mixin/requester.cpp (hunk 4 above)
Comment (riemass) [reply libcaf_core/tests/legacy/mixin/requester.cpp:370]: I guess I can keep the client in scope and expect the ref count to drop to 1.

File: libcaf_core/tests/legacy/mixin/requester.cpp (hunk 5 above)
Comment (Neverlord) [reply libcaf_core/tests/legacy/mixin/requester.cpp:382]: Ahh! Yeah, now it makes sense. Sorry for being a bit slow.

To make the test a bit more "digestible", I'd recommend explicitly triggering the `request` to start with a ref count of 1. Something like this:

```c++
  auto server = sys.spawn(...);
  auto client = actor_cast<strong_actor_ptr>(sys.spawn(...));
  run();
  CHECK_EQ(client->strong_refs, 1u);
  inject((actor), with(server).to(client));
  CHECK(sched.has_pending_timeout());
  expect((int, int), from(client).to(server));
  expect((int), from(server).to(client));
  CHECK(!sched.has_pending_timeout());
  // The scheduler may no longer hold a reference to the client.
  CHECK_EQ(client->strong_refs, 1u);
```

File: libcaf_core/tests/legacy/mixin/requester.cpp (hunk 3 above)
Comment (Neverlord) [reply libcaf_core/tests/legacy/mixin/requester.cpp:367]: All right, since it's a quite subtle issue, let's just name the test `TEST_CASE("GH-698 regression")`.

File: libcaf_core/caf/action.hpp [hunk 6]
```diff
@@ -156,8 +162,9 @@ struct default_action_impl : detail::atomic_ref_counted, action::impl {
   void run() override {
     if (state_.load() == action::state::scheduled) {
       f_();
-      if constexpr (IsSingleShot)
-        state_ = action::state::disposed;
+      if constexpr (IsSingleShot) {
+        dispose();
+      }
```
Comment (Neverlord) [inline libcaf_core/caf/action.hpp:167]: This code can now run into UB, e.g. segfault or do other weird stuff.

- Thread 1 is calling run() and passes line 164
- Thread 2 is calling dispose() and runs the destructor of f_
- Thread 1 calls f_(): boom; accessing a destructed object

There's an easy fix for single-shot actions, but multi-shot actions are tricky to implement lock-free. The multi-shot type is used much more widely in the code base, so we need a good solution here.

**Review by Neverlord — CHANGES_REQUESTED** [review]

File: libcaf_core/caf/action.hpp [hunk 7]
```diff
@@ -132,34 +136,87 @@ inline bool operator!=(const action& lhs, const action& rhs) noexcept {
...
+    auto expected = action::state::scheduled;
+    if (!state_.compare_exchange_strong(expected, action::state::disposed))
+      return;
+    f_();
+    f_.~F();
+    return;
+  }
+
+  void run_multi_shot() {
+    // We can only run a scheduled action
```
Comment (Neverlord) [inline libcaf_core/caf/action.hpp:197]:
```suggestion
    // We can only run a scheduled action.
```

File: libcaf_core/caf/action.test.cpp [hunk 8]
```diff
@@ -35,6 +38,25 @@ SCENARIO("actions wrap function calls") {
...
+        called = true;
+        uut_ptr->dispose();
+        check_eq(uut_ptr->ptr()->current_state(),
+                 action::state::deferred_dispose);
+      });
+      uut_ptr = &uut;
+      THEN("it transitions to deferred_dispose") {
+        check(uut.scheduled());
+        uut.run();
+        check(called);
```
Comment (Neverlord) [inline libcaf_core/caf/action.test.cpp:54]: Good idea writing the test like this to guarantee the action ending up the deferred dispose path. 👍

One nitpick: I'd keep the checks in the `THEN` block since we spell out the expected transition there but don't actually check it:

```suggestion
      });
      uut_ptr = &uut;
      THEN("it transitions to deferred_dispose") {
        check(uut.scheduled());
        uut.run();
        check(called);
        check_eq(uut_ptr->ptr()->current_state(),
                 action::state::deferred_dispose);
```

File: libcaf_core/caf/action.test.cpp [hunk 9]
```diff
@@ -35,6 +38,25 @@ SCENARIO("actions wrap function calls") {
...
+    WHEN("disposing an running action") {
+      auto called = false;
+      action* uut_ptr = nullptr;
+      auto uut = make_action([this, &called, &uut_ptr] {
+        called = true;
+        uut_ptr->dispose();
+        check_eq(uut_ptr->ptr()->current_state(),
+                 action::state::deferred_dispose);
+      });
+      uut_ptr = &uut;
```
Comment (Neverlord) [inline libcaf_core/caf/action.test.cpp:50]: I suppose this whole `uut_ptr` setup is to have the action refer back to itself? Unless I miss something, I think it could still be a bit less verbose like this:

```suggestion
      action uut;
      uut = make_action([&called, &uut] {
        called = true;
        uut.dispose();
      });
```

File: libcaf_core/caf/action.test.cpp [hunk 10]
```diff
@@ -55,6 +77,41 @@ SCENARIO("actions wrap function calls") {
...
+    WHEN("running the action once") {
+      auto called = false;
+      auto uut = make_single_shot_action([&called] { called = true; });
+      THEN("it transitions to disposed") {
+        check(uut.scheduled());
+        uut.run();
+        check(called);
+        check(uut.disposed());
+      }
+      AND_THEN("run no longer calls the lambda") {
```
Comment (Neverlord) [inline libcaf_core/caf/action.test.cpp:90]:
```suggestion
      AND_THEN("running the action again has no effect") {
```

File: libcaf_core/caf/action.hpp [hunk 11]
```diff
@@ -132,34 +136,87 @@ inline bool operator!=(const action& lhs, const action& rhs) noexcept {
...
+    expected = state_.load();
+    if (expected == action::state::running
+        && state_.compare_exchange_strong(expected, action::state::scheduled))
+      return;
+    if (expected == action::state::deferred_dispose
+        && state_.compare_exchange_strong(expected, action::state::disposed)) {
+      f_.~F();
+      return;
+    }
+    CAF_RAISE_ERROR("Invalid state found after running an action.");
```
[the remark this answers is not in the document]
Comment (riemass) [reply libcaf_core/caf/action.hpp:212]: I see what you did there. I agree with the changes, but I think without the line:
`auto expected = state_.load();`
expected would be left as `action::state::scheduled`, since compare exchange does nothing to expected if it succeeds.

File: libcaf_core/caf/action.test.cpp (hunk 9 above)
Comment (riemass) [reply libcaf_core/caf/action.test.cpp:50]: Good point. I also need the check_eq inside the lambda.

File: libcaf_core/caf/action.test.cpp (hunk 8 above)
Comment (riemass) [reply libcaf_core/caf/action.test.cpp:54]: I can't really refactor it like this since after finishing `run` the action would go to the `disposed` state. I need a check that is triggered during the `run` and asks for `deferred_dispose`.

Comment (Neverlord) [reply libcaf_core/caf/action.test.cpp]: Yeah, good point. Didn't think of that. :)

**Review by Neverlord — APPROVED** [review]
