### PR TITLE
Reduce stack usage and indirections in serializers

### LINKED ISSUE #912: High stack usage of serializers
Passing a struct with many members (≥100) to a serializer or deserializer can cause a stack overflow. One of the culprits is `apply_derived` in `data_processor` that essentially doubles the stack depth (we assumed compilers to inline these calls, but that appears to not work as expected).

### PR DESCRIPTION
**Pull request by Neverlord**
Optimize `data_processor` in order to reduce the risk of stack overflows when using classes with many (≥100) data members.

Close #912.

### CODE REVIEW

File: libcaf_core/src/error.cpp [hunk 1]
```diff
@@ -19,10 +19,11 @@
 #include "caf/error.hpp"
 
 #include "caf/config.hpp"
+#include "caf/deep_to_string.hpp"
+#include "caf/deserializer.hpp"
```
Comment (jakobod) [inline libcaf_core/src/error.cpp]: Is this include necessary?

File: libcaf_core/src/error.cpp [hunk 2]
```diff
@@ -19,10 +19,11 @@
...
+#include "caf/make_message.hpp"
 #include "caf/message.hpp"
 #include "caf/serializer.hpp"
```
Comment (jakobod) [inline libcaf_core/src/error.cpp]: This seems unecessary too.
