### PR TITLE
Fix compilation error in Clang 20 for json::value::member operator==

### LINKED ISSUE #2092: Build fail with Clang 20 and libstdc++-15 `invalid operands to binary expression ('const caf::detail::json::value::member' and 'const caf::detail::json::value::member')`
```
$ CC=clang-20 CXX=clang++-20 cmake -B build && cmake --build build -j
-- The CXX compiler identification is Clang 20.1.7
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-20 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")
-- Build CAF with C++17
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Performing Test has_64bit_atomic
-- Performing Test has_64bit_atomic - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Warning (dev) at examples/CMakeLists.txt:7 (install):
  Policy CMP0177 is not set: install() DESTINATION paths are normalized.  Run
  "cmake --help-policy CMP0177" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  examples/CMakeLists.txt:13 (add_example)
  examples/CMakeLists.txt:20 (add_core_example)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at examples/CMakeLists.txt:7 (install):
  Policy CMP0177 is not set: install() DESTINATION paths are normalized.  Run
  "cmake --help-policy CMP0177" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  examples/CMakeLists.txt:13 (add_example)
  examples/CMakeLists.txt:21 (add_core_example)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (1.4s)
-- Generating done (0.1s)

...

[  4%] Building CXX object libcaf_core/CMakeFiles/libcaf_core.dir/caf/detail/json.cpp.o
In file included from /home/rlozko/git/actor-framework/libcaf_core/caf/detail/json.cpp:5:
In file included from /home/rlozko/git/actor-framework/libcaf_core/caf/detail/json.hpp:7:
In file included from /home/rlozko/git/actor-framework/libcaf_core/caf/detail/mbr_list.hpp:7:
In file included from /home/rlozko/git/actor-framework/libcaf_core/caf/detail/monotonic_buffer_resource.hpp:11:
In file included from /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/map:64:
In file included from /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_tree.h:65:
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_algobase.h:1656:22: error: invalid operands to binary expression ('const caf::detail::json::value::member' and 'const caf::detail::json::value::member')
 1656 |             if (!(*__first1 == *__first2))
      |                   ~~~~~~~~~ ^  ~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_algobase.h:1720:30: note: in instantiation of function template specialization 'std::__equal4<caf::detail::mbr_list_iterator<const caf::detail::json::value::member>, caf::detail::mbr_list_iterator<const caf::detail::json::value::member>>' requested here
 1720 |       return _GLIBCXX_STD_A::__equal4(__first1, __last1, __first2, __last2);
      |                              ^
/home/rlozko/git/actor-framework/libcaf_core/caf/detail/mbr_list.hpp:260:15: note: in instantiation of function template specialization 'std::equal<caf::detail::mbr_list_iterator<const caf::detail::json::value::member>, caf::detail::mbr_list_iterator<const caf::detail::json::value::member>>' requested here
  260 |   return std::equal(lhs.begin(), lhs.end(), rhs.begin(), rhs.end());
      |               ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1271:20: note: in instantiation of function template specialization 'caf::detail::operator==<caf::detail::json::value::member>' requested here
 1271 |                                     return __l == __r;
      |                                                ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1249:13: note: in instantiation of function template specialization 'std::operator==(const variant<null_t, long, unsigned long, double, bool, basic_string_view<char, char_traits<char>>, mbr_list<value>, mbr_list<member>, undefined_t> &, const variant<null_t, long, unsigned long, double, bool, basic_string_view<char, char_traits<char>>, mbr_list<value>, mbr_list<member>, undefined_t> &)::(anonymous class)::operator()<const caf::detail::mbr_list<caf::detail::json::value::member> &, const caf::detail::mbr_list<caf::detail::json::value::member> &>' requested here
 1249 |                   __ret = __op(__this_mem, __rhs_mem);
      |                           ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/type_traits:2781:7: note: in instantiation of function template specialization 'std::__detail::__variant::__compare(bool, const std::variant<caf::detail::json::null_t, long, unsigned long, double, bool, std::basic_string_view<char>, caf::detail::mbr_list<caf::detail::json::value>, caf::detail::mbr_list<caf::detail::json::value::member>, caf::detail::json::undefined_t> &, const std::variant<caf::detail::json::null_t, long, unsigned long, double, bool, std::basic_string_view<char>, caf::detail::mbr_list<caf::detail::json::value>, caf::detail::mbr_list<caf::detail::json::value::member>, caf::detail::json::undefined_t> &, (lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1270:7))::(anonymous class)::operator()<const caf::detail::mbr_list<caf::detail::json::value::member> &, std::integral_constant<unsigned long, 7>>' requested here
 2781 |       std::declval<_Fn>()(std::declval<_Args>()...)
      |       ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/type_traits:2792:29: note: while substituting deduced template arguments into function template '_S_test' [with _Fn = (lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1242:2), _Args = (no value)]
 2792 |       using type = decltype(_S_test<_Functor, _ArgTypes...>(0));
      |                             ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/type_traits:2798:14: note: in instantiation of template class 'std::__result_of_impl<false, false, (lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1242:2), const caf::detail::mbr_list<caf::detail::json::value::member> &, std::integral_constant<unsigned long, 7>>' requested here
 2798 |     : public __result_of_impl<
      |              ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/invoke.h:91:24: note: in instantiation of template class 'std::__invoke_result<(lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1242:2), const caf::detail::mbr_list<caf::detail::json::value::member> &, std::integral_constant<unsigned long, 7>>' requested here
   91 |     constexpr typename __invoke_result<_Callable, _Args...>::type
      |                        ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1044:4: note: while substituting deduced template arguments into function template '__invoke' [with _Callable = (lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1242:2), _Args = <const caf::detail::mbr_list<caf::detail::json::value::member> &, integral_constant<size_t, 7UL>>]
 1044 |           std::__invoke(std::forward<_Visitor>(__visitor),
      |           ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1898:5: note: in instantiation of member function 'std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__variant_idx_cookie (*)((lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1242:2) &&, const std::variant<caf::detail::json::null_t, long, unsigned long, double, bool, std::basic_string_view<char>, caf::detail::mbr_list<caf::detail::json::value>, caf::detail::mbr_list<caf::detail::json::value::member>, caf::detail::json::undefined_t> &)>, std::integer_sequence<unsigned long, 7>>::__visit_invoke' requested here
 1898 |                   _GLIBCXX_VISIT_CASE(7)
      |                   ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1883:4: note: expanded from macro '_GLIBCXX_VISIT_CASE'
 1883 |           __visit_invoke(std::forward<_Visitor>(__visitor),             \
      |           ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:187:12: note: in instantiation of function template specialization 'std::__do_visit<std::__detail::__variant::__variant_idx_cookie, (lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1242:2), const std::variant<caf::detail::json::null_t, long, unsigned long, double, bool, std::basic_string_view<char>, caf::detail::mbr_list<caf::detail::json::value>, caf::detail::mbr_list<caf::detail::json::value::member>, caf::detail::json::undefined_t> &>' requested here
  187 |       std::__do_visit<__variant_idx_cookie>(std::forward<_Visitor>(__visitor),
      |            ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1241:18: note: in instantiation of function template specialization 'std::__detail::__variant::__raw_idx_visit<(lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1242:2), const std::variant<caf::detail::json::null_t, long, unsigned long, double, bool, std::basic_string_view<char>, caf::detail::mbr_list<caf::detail::json::value>, caf::detail::mbr_list<caf::detail::json::value::member>, caf::detail::json::undefined_t> &>' requested here
 1241 |       __variant::__raw_idx_visit(
      |                  ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1269:25: note: in instantiation of function template specialization 'std::__detail::__variant::__compare<bool, std::variant<caf::detail::json::null_t, long, unsigned long, double, bool, std::basic_string_view<char>, caf::detail::mbr_list<caf::detail::json::value>, caf::detail::mbr_list<caf::detail::json::value::member>, caf::detail::json::undefined_t>, (lambda at /usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/variant:1270:7)>' requested here
 1269 |       return __variant::__compare(true, __lhs, __rhs,
      |                         ^
/home/rlozko/git/actor-framework/libcaf_core/caf/detail/json.hpp:189:19: note: in instantiation of function template specialization 'std::operator==<caf::detail::json::null_t, long, unsigned long, double, bool, std::basic_string_view<char>, caf::detail::mbr_list<caf::detail::json::value>, caf::detail::mbr_list<caf::detail::json::value::member>, caf::detail::json::undefined_t>' requested here
  189 |   return lhs.data == rhs.data;
      |                   ^
/home/rlozko/git/actor-framework/libcaf_core/caf/detail/json.hpp:44:16: note: candidate function not viable: no known conversion from 'const caf::detail::json::value::member' to 'null_t' for 1st argument
   44 | constexpr bool operator==(null_t, null_t) {
      |                ^          ~~~~~~
/home/rlozko/git/actor-framework/libcaf_core/caf/detail/json.hpp:54:16: note: candidate function not viable: no known conversion from 'const caf::detail::json::value::member' to 'undefined_t' for 1st argument
   54 | constexpr bool operator==(undefined_t, undefined_t) {
      |                ^          ~~~~~~~~~~~
/home/rlozko/git/actor-framework/libcaf_core/caf/detail/json.hpp:188:13: note: candidate function not viable: no known conversion from 'const caf::detail::json::value::member' to 'const value' for 1st argument
  188 | inline bool operator==(const value& lhs, const value& rhs) {
      |             ^          ~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_pair.h:1060:5: note: candidate template ignored: could not match 'const pair<_T1, _T2>' against 'const caf::detail::json::value::member'
 1060 |     operator==(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
      |     ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_iterator.h:443:5: note: candidate template ignored: could not match 'const reverse_iterator<_Iterator>' against 'const caf::detail::json::value::member'
  443 |     operator==(const reverse_iterator<_Iterator>& __x,
      |     ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_iterator.h:488:5: note: candidate template ignored: could not match 'const reverse_iterator<_IteratorL>' against 'const caf::detail::json::value::member'
  488 |     operator==(const reverse_iterator<_IteratorL>& __x,
      |     ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_iterator.h:1662:5: note: candidate template ignored: could not match 'const move_iterator<_IteratorL>' against 'const caf::detail::json::value::member'
 1662 |     operator==(const move_iterator<_IteratorL>& __x,
      |     ^
/usr/lib/gcc/x86_64-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_iterator.h:1732:5: note: candidate template ignored: could not match 'const move_iterator<_Iterator>' against 'const caf::detail::json::value::member'
 1732 |     operator==(const move_iterator<_Iterator>& __x,
      |     ^
1 error generated.
```
GCC 15 by itself builds without errors, maybe there is something wrong with Clang 20.

```
$ git log -n1
commit faddf2e15ce6caa420fcb0a355e21cd89aaa21d7 (HEAD -> main, origin/main, origin/HEAD)
Merge: 0f4157d03 ea68b6438
Author: Dominik Charousset <dominik@charousset.de>
Date:   Sun Jun 8 19:12:18 2025 +0300
                                                                                                                                                                                                                                                                                                                                                                                                  Merge pull request #2090

    Fix ASAN false positive in json_reader test
```

### PR DESCRIPTION
**Pull request by riemass**
Closes #2092.
The operator== for `json::value` and `json::value::member` call each other. Reordering them and moving one to the implementation file solved the issue for Clang v20.1.0.

### CODE REVIEW

File: libcaf_core/caf/detail/json.hpp [hunk 1]
```diff
@@ -185,6 +185,10 @@ class CAF_CORE_EXPORT value {
   }
 };
 
+bool operator==(const value::member& lhs, const value::member& rhs);
+
+bool operator!=(const value::member& lhs, const value::member& rhs);
```
Comment (Neverlord) [inline libcaf_core/caf/detail/json.hpp]:
```suggestion
inline bool operator==(const value::member& lhs, const value::member& rhs) {
  return value::equals(lhs, rhs);
}

inline bool operator!=(const value::member& lhs, const value::member& rhs) {
  return !(lhs == rhs);
}
```

And then add/implement `equals`.

**Review by Neverlord — CHANGES_REQUESTED** [review]
Thanks for tackling this. Unfortunately, this will trade a compiler error for linker errors since the new operators are not exported. However, I would prefer they'd stay inline and instead `operator==` can dispatch to a new static function on `value` (see review comment).

File: libcaf_core/caf/detail/json.hpp (hunk 1 above)
Comment (riemass) [reply libcaf_core/caf/detail/json.hpp]: Forgot to export...
Implemented equals as inline, otherwise I suppose it makes little sense.

**Review by Neverlord — APPROVED** [review]
