### PR TITLE
Fix infinite recursion in read_ini

### LINKED ISSUE #894: endless loop while parsing a config file if line starts with a non-alphanumeric character
Let's take a minimal program minapp.cpp:
`#include "caf/exec_main.hpp"`
``void caf_main(caf::actor_system& system)``
`{`
`}`
`CAF_MAIN()`

and a minimal config file caf-application.ini with 1 line and 1 character:
`#`
Running it as
`minapp --config-file=caf-application.ini`
goes into endless loop, without error diagnostics.

Looks like it is endlessly bouncing in libcaf_core/caf/detail/parser/read_ini.hpp, in read_ini() between term_state(init) and unstable_state(return_to_global).

The same effect if '#" in config file is replaced with '/', '\', '.', ',', '!', '@', '$', '%', , '^', '&', '('.

### PR DESCRIPTION
**Pull request by Neverlord**
Close #894.

### CODE REVIEW

File: libcaf_core/test/read_ini.cpp [hunk 1]
```diff
@@ -242,6 +242,14 @@ const auto ini1_log = make_log(
 );
 // clang-format on
 
+const char* ini2 = "#";
```
Comment (josephnoir) [inline libcaf_core/test/read_ini.cpp]: This  and `ini3` below could be `auto` as well, right?
