### PR TITLE
Raise error when opening user-defined config fails

### LINKED ISSUE #947: Config file could be silently ignored, application can run with unintended parameters
Attachment [demo_files.tar.gz](https://github.com/actor-framework/actor-framework/files/3769372/demo_files.tar.gz) contains a minimal CAF application which uses CAF built-in feature for parsing and getting a user-defined parameter from the config file.

It works as expected when the config file exists and is accessible via absolute pathname or a simple relative pathname:
```
$ ./myapp --config-file=/home/user/my_app.ini
DebugLevel = 4
$ ./myapp --config-file=my_app.ini
DebugLevel = 4
$ ./myapp --config-file=./my_app.ini
DebugLevel = 4
$ ./myapp --config-file=../user/my_app.ini
DebugLevel = 4
```
However, it silently ignores a non-existing config file or one with '~':
```
$ ./myapp --config-file=zzzzzz
DebugLevel = 65535
$ ./myapp --config-file=~/my_app.ini
DebugLevel = 65535
```
I expected that the application stops with error message about a problem with config file.

### PR DESCRIPTION
**Pull request by Neverlord**
Closes #947.

### CODE REVIEW

File: libcaf_core/src/actor_system_config.cpp [hunk 1]
```diff
@@ -516,6 +521,7 @@ error actor_system_config::extract_config_file_path(string_list& args) {
   auto evalue = ptr->parse(path);
   if (!evalue)
     return std::move(evalue.error());
+  put(content, "config-file", *evalue);
```
Comment (josephnoir) [inline libcaf_core/src/actor_system_config.cpp]: How does this relate to the addresses issue? Parse already failed here if the config file is not available.

Comment (Neverlord) [reply libcaf_core/src/actor_system_config.cpp]: `extract_config_file_path` gets called before parsing any other CLI option. The work flow is basically:
- check if there's a `--config-file=` in the CLI arguments
- if yes: parse that argument (but not any other)
- read the config file
- read the CLI arguments

By putting `config-file` into our `content` map, we have access to the information whether the user has requested to read that file or if we simply try opening the default.

Comment (josephnoir) [reply libcaf_core/src/actor_system_config.cpp]: Ok.
