### PR TITLE
Fix "mutex destroyed while busy" error on MSVC

### LINKED ISSUE #1371: async.blocking_consumer crashes on MSVC
With the newer MSVC version, our unit tests in `async.blocking_consumer` started to crash:

```
+----------------------------------------------------------------------+
                        async.blocking_consumer
+----------------------------------------------------------------------+

- SCENARIO blocking consumers allow threads to receive data
ModLoad: 00007ffb`72a10000 00007ffb`72a22000   C:\Windows\SYSTEM32\kernel.appcore.dll
ModLoad: 00007ffb`75590000 00007ffb`7562e000   C:\Windows\System32\msvcrt.dll
  -> GIVEN a producers running in a separate thread [line 42]
  -> WHEN consuming the generated value with a blocking consumer [line 43]
  -> THEN the consumer receives all values in order [line 44]
D:\a\_work\1\s\src\vctools\crt\github\stl\src\mutex.cpp(61): mutex destroyed while busy
Debug Error!

Program: ...boxuser\Desktop\caf\build\libcaf_core\Debug\caf-core-test.exe

abort() has been called

(Press Retry to debug the application)
ntdll!NtTerminateProcess+0x14:
00007ffb`7746d2f4 c3              ret
0:000> k
Child-SP          RetAddr               Call Site
000000b2`d4b7bf28 00007ffb`7742da38     ntdll!NtTerminateProcess+0x14
000000b2`d4b7bf30 00007ffb`7624e0ab     ntdll!RtlExitUserProcess+0xb8
000000b2`d4b7bf60 00007ffb`3cf61eda     KERNEL32!FatalExit+0xb
000000b2`d4b7bf90 00007ffb`3cf61e85     ucrtbased!wassert+0x65a
000000b2`d4b7bfc0 00007ffb`3cf62109     ucrtbased!wassert+0x605
000000b2`d4b7c020 00007ffb`3cf5ae8b     ucrtbased!Exit+0x19
000000b2`d4b7c050 00007ffb`63fc3341     ucrtbased!abort+0x7b
000000b2`d4b7c090 00007ffb`63fc3012     MSVCP140D!Thrd_abort+0x41
*** WARNING: Unable to verify checksum for caf-core-test.exe
000000b2`d4b7c0c0 00007ff6`49ef15cc     MSVCP140D!Mtx_destroy_in_situ+0x22
000000b2`d4b7c100 00007ff6`49ef1dc4     caf_core_test!std::_Mutex_base::~_Mutex_base+0x1c
000000b2`d4b7c130 00007ff6`4a074d08     caf_core_test!std::mutex::~mutex+0x14
000000b2`d4b7c160 00007ff6`4a075918     caf_core_test!caf::async::spsc_buffer<int>::~spsc_buffer<int>+0x78
000000b2`d4b7c190 00007ff6`4ae99ab4     caf_core_test!caf::async::spsc_buffer<int>::`scalar deleting destructor'+0x18
000000b2`d4b7c1c0 00007ff6`49f15874     caf_core_test!caf::detail::atomic_ref_counted::deref+0x74
000000b2`d4b7c210 00007ff6`4a077d94     caf_core_test!caf::intrusive_ptr_release+0x14
000000b2`d4b7c240 00007ff6`4a077fb8     caf_core_test!caf::intrusive_ptr_access<caf::async::spsc_buffer<int> >::release+0x14
000000b2`d4b7c270 00007ff6`4a075001     caf_core_test!caf::intrusive_ptr<caf::async::spsc_buffer<int> >::reset+0x48
000000b2`d4b7c2b0 00007ff6`4a072804     caf_core_test!caf::intrusive_ptr<caf::async::spsc_buffer<int> >::operator=+0x21
000000b2`d4b7c2e0 00007ff6`4a07262f     caf_core_test!caf::async::blocking_consumer<int>::impl::pull<caf::async::delay_errors_t,caf::none_t>+0x1b4
000000b2`d4b7c3b0 00007ff6`4a0725e9     caf_core_test!caf::async::blocking_consumer<int>::impl::pull<caf::async::delay_errors_t>+0x2f
000000b2`d4b7c3e0 00007ff6`4a06dcc6     caf_core_test!caf::async::blocking_consumer<int>::pull<caf::async::delay_errors_t>+0x39
000000b2`d4b7c420 00007ff6`4a06e47d     caf_core_test!tests39::`anonymous namespace'::test41::run_test_impl+0x1a66
000000b2`d4b7d600 00007ff6`49e5acdd     caf_core_test!caf::test::test_impl<tests39::`anonymous namespace'::test41>::run_test_impl+0x4d
000000b2`d4b7de70 00007ff6`49e595b0     caf_core_test!caf::test::engine::run+0x84d
000000b2`d4b7ec80 00007ff6`49e5ec96     caf_core_test!caf::test::main+0x18a0
000000b2`d4b7fa40 00007ff6`4b13d099     caf_core_test!main+0x26
000000b2`d4b7fa70 00007ff6`4b13cf7e     caf_core_test!invoke_main+0x39
000000b2`d4b7fac0 00007ff6`4b13ce3e     caf_core_test!__scrt_common_main_seh+0x12e
000000b2`d4b7fb30 00007ff6`4b13d12e     caf_core_test!__scrt_common_main+0xe
000000b2`d4b7fb60 00007ffb`76247034     caf_core_test!mainCRTStartup+0xe
000000b2`d4b7fb90 00007ffb`77422651     KERNEL32!BaseThreadInitThunk+0x14
000000b2`d4b7fbc0 00000000`00000000     ntdll!RtlUserThreadStart+0x21
0:000> client_loop: send disconnect: Broken pipe
```

### PR DESCRIPTION
**Pull request by Neverlord**
Closes #1371.

### CODE REVIEW

File: libcaf_core/caf/async/blocking_consumer.hpp [hunk 1]
```diff
@@ -45,6 +45,7 @@ class blocking_consumer {
           return read_result::try_again_later;
       }
       auto [again, n] = buf_->pull_unsafe(guard, policy, 1u, *this);
+      guard.unlock();
```
Comment (josephnoir) [inline libcaf_core/caf/async/blocking_consumer.hpp:48]: Can this function be called in parallel? Then, the check in line 36 could happen before the assignment in 49/50.

Comment (Neverlord) [reply libcaf_core/caf/async/blocking_consumer.hpp:48]: This function itself cannot run in parallel. A `blocking_consumer` is for one caller/thread only.

**Review by josephnoir — APPROVED** [review]
